name: Release
on:
  push:
    tags: [v*.*.*]

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Meadows ${{ github.ref }}
          draft: false
          prerelease: false

  build-release:
    needs: release
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact: linux
          - os: macos-latest
            artifact: macos
          - os: windows-latest
            artifact: windows
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: KyleMayes/install-llvm-action@v1
        with:
          version: 17
      - uses: jwlawson/actions-setup-cmake@v2
      - name: Build Release
        run: |
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTS=ON
          cmake --build build --parallel
      - name: Package
        run: ./scripts/ci/package_release.sh
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: release/
          asset_name: meadows-${{ matrix.artifact }}
          asset_content_type: application/zip